// Code generated by protoc-gen-go.
// source: proto/gelm.proto
// DO NOT EDIT!

/*
Package gelm is a generated protocol buffer package.

It is generated from these files:
	proto/gelm.proto

It has these top-level messages:
	Message
*/
package gelm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Enum int32

const (
	Enum_ENUM_VALUE_DEFAULT Enum = 0
	Enum_ENUM_VALUE_1       Enum = 1
	Enum_ENUM_VALUE_2       Enum = 2
)

var Enum_name = map[int32]string{
	0: "ENUM_VALUE_DEFAULT",
	1: "ENUM_VALUE_1",
	2: "ENUM_VALUE_2",
}
var Enum_value = map[string]int32{
	"ENUM_VALUE_DEFAULT": 0,
	"ENUM_VALUE_1":       1,
	"ENUM_VALUE_2":       2,
}

func (x Enum) Enum() *Enum {
	p := new(Enum)
	*p = x
	return p
}
func (x Enum) String() string {
	return proto.EnumName(Enum_name, int32(x))
}
func (x *Enum) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Enum_value, data, "Enum")
	if err != nil {
		return err
	}
	*x = Enum(value)
	return nil
}
func (Enum) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Message struct {
	Id                *int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FieldWithLongName *string `protobuf:"bytes,2,opt,name=field_with_long_name" json:"field_with_long_name,omitempty"`
	Enum              *Enum   `protobuf:"varint,3,opt,name=enum,enum=Enum" json:"enum,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Message) GetFieldWithLongName() string {
	if m != nil && m.FieldWithLongName != nil {
		return *m.FieldWithLongName
	}
	return ""
}

func (m *Message) GetEnum() Enum {
	if m != nil && m.Enum != nil {
		return *m.Enum
	}
	return Enum_ENUM_VALUE_DEFAULT
}

func init() {
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterEnum("Enum", Enum_name, Enum_value)
}

var fileDescriptor0 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4f, 0xcd, 0xc9, 0xd5, 0x03, 0x33, 0x95, 0x3c, 0xb8, 0xd8, 0x7d, 0x53, 0x8b,
	0x8b, 0x13, 0xd3, 0x53, 0x85, 0xb8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98,
	0x85, 0x64, 0xb8, 0x44, 0xd2, 0x32, 0x53, 0x73, 0x52, 0xe2, 0xcb, 0x33, 0x4b, 0x32, 0xe2, 0x73,
	0xf2, 0xf3, 0xd2, 0xe3, 0xf3, 0x12, 0x73, 0x53, 0x25, 0x98, 0x80, 0xb2, 0x9c, 0x42, 0xc2, 0x5c,
	0x2c, 0xa9, 0x79, 0xa5, 0xb9, 0x12, 0xcc, 0x40, 0x1e, 0x9f, 0x11, 0xab, 0x9e, 0x2b, 0x90, 0xa3,
	0xe5, 0xc4, 0xc5, 0x02, 0xa2, 0x85, 0xc4, 0xb8, 0x84, 0x5c, 0xfd, 0x42, 0x7d, 0xe3, 0xc3, 0x1c,
	0x7d, 0x42, 0x5d, 0xe3, 0x5d, 0x5c, 0xdd, 0x1c, 0x43, 0x7d, 0x42, 0x04, 0x18, 0x84, 0x04, 0xb8,
	0x78, 0x90, 0xc4, 0x0d, 0x05, 0x18, 0xd1, 0x44, 0x8c, 0x04, 0x98, 0x00, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xeb, 0xe6, 0x5c, 0xad, 0xa0, 0x00, 0x00, 0x00,
}
